[formatting]
align_entries = false
align_comments = true
align_single_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = false
compact_arrays = true
compact_inline_tables = false
compact_entries = false
column_width = 80
indent_tables = false
indent_entries = false
inline_table_expand = true
trailing_newline = true
allowed_blank_lines = 2
indent_string = "  "
reorder_keys = false
reorder_arrays = false
crlf = false
