---
pre-commit:
  commands:
    detect-file-over-limit-size: &detect-file
      run: |
        sh .lefthook/file/detect_file_over_limit_size/main.sh \
          {staged_files}

pre-push:
  commands:
    detect-file-over-limit-size:
      <<: *detect-file
      run: |
        sh .lefthook/file/detect_file_over_limit_size/main.sh \
          {push_files}

lint:
  commands:
    detect-file-over-limit-size: &detect-file-from-all-files
      <<: *detect-file
      run: |
        sh .lefthook/file/detect_file_over_limit_size/main.sh \
          {all_files}

lint-fix:
  commands:
    detect-file-over-limit-size: *detect-file-from-all-files
