---
name: Install Node packages
description: Install Node packages with npm

runs:
  using: composite
  steps:
    - name: Install Node
      # yamllint disable-line rule:line-length
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        check-latest: false
        # Decides a node version from `engines.node` in `package.json`
        # https://github.com/actions/setup-node/blob/b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8/docs/advanced-usage.md#node-version-file
        # v4.0.1 Commit on 2023-12-18
        node-version-file: package.json
        cache: npm

    - name: Install Node packages with npm
      run: npm ci
      shell: bash
