---
pre-commit:
  commands:
    insert-final-newline: &insert-final-newline
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {staged_files}
      stage_fixed: true

pre-push:
  commands:
    detect-file-without-final-newline:
      <<: *insert-final-newline
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {push_files}

        git diff --exit-code {push_files}

lint-fix:
  commands:
    insert-final-newline: &insert-final-newline-from-all-files
      <<: *insert-final-newline
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {all_files}
