---
pre-commit:
  commands:
    insert-final-newline: &insert
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {staged_files}
      stage_fixed: true
      tags:
        - style
        # Because uses `sed` command in `main.sh`.
        - always-update-modify-time

pre-push:
  commands:
    detect-file-without-final-newline: &detect
      <<: *insert
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {push_files}

        git diff --exit-code --quiet {push_files}

pre-merge-commit:
  commands:
    detect-file-without-final-newline:
      <<: *detect
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {staged_files}

        git diff --exit-code --quiet {staged_files}

lint-fix:
  commands:
    insert-final-newline:
      <<: *insert
      run: |
        sh .lefthook/style/insert_final_newline/main.sh \
          {all_files}
