---
name: Detect

on:
  push:
    branches-ignore:
      - renovate/*

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  # tag::style[]
  # `tag::<TAG_NAME>[]` and `end::<TAG_NAME>[]` used to write document.
  # `<TAG_NAME>` used to tag attribute of include directive in AsciiDoc.
  # https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions
  style:
    name: Style
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create a timeline of GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@fbbb6f71498dbdb3af862970133257532cd48054 # v1.0.0
        with:
          github-token: ${{ github.token }}

      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          # Because to run `lefthook run lint-fix`.
          disable-file-monitoring: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install task runner
        uses: ./.github/actions/setup_tool_version_manager

      - name: Detect Trailing Space
        run: |
          lefthook run lint \
            --commands detect-trailing-space

      - name: Detect Trailing Blank Line
        run: |
          lefthook run lint-fix \
            --commands trim-trailing-blank-line

          git diff --exit-code --color=always
  # end::style[]
