---
name: Detect

on:
  push:
    branches-ignore:
      - renovate/*

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  # tag::style[]
  # `tag::<TAG_NAME>[]` and `end::<TAG_NAME>[]` used to write document.
  # `<TAG_NAME>` used to tag attribute of include directive in AsciiDoc.
  # https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions
  style:
    name: Style
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install task runner
        uses: ./.github/actions/install_tools_with_aqua

      - name: Detect trailing space
        run: |
          lefthook run lint \
            --commands detect-trailing-space
  # end::style[]
  # tag::timeline[]
  create_timeline:
    name: Create timeline of this GitHub Actions workflow
    if: ${{ always() }}
    needs:
      - style
    runs-on: ubuntu-22.04
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@37c6155f2e2fc1a056abe1108c9ca61975a6e4f8 # v2.0.0
        with:
          github-token: ${{ github.token }}
  # end::timeline[]
