---
name: Test setup

on:
  push:
    paths:
      - scripts/setup.sh
      - scripts/install_aqua.sh
      - .aqua/aqua.yml
      - .aqua/imports/*.yml
      - .aqua/aqua-checksums.json
      - package.json
      - package-lock.json
      - .ruby-version
      - .lefthook.yml
      - .lefthook/**/*.yml
      - .github/workflows/test_setup.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@baa62e018ca5504e2d617502ce1eacf9171e757a # v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          disable-sudo: true
          # Because to run `npm install` on `bash scripts/setup.sh`.
          disable-file-monitoring: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download aqua
        run: bash scripts/deps/download_aqua.sh

      - name: Add aqua to the environment variable `PATH`
        run: |
          # References
          # https://aquaproj.github.io/docs/tutorial/#install-aqua
          echo "$HOME/.local/share/aquaproj-aqua/bin" >> "$GITHUB_PATH"

      - name: Install Node
        # yamllint disable-line rule:line-length
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          check-latest: false
          # Decides a node version from `engines.node` in `package.json`
          # https://github.com/actions/setup-node/blob/b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8/docs/advanced-usage.md#node-version-file
          # v4.0.1 Commit on 2023-12-18
          node-version-file: package.json
          cache: ""

      - name: Run setup
        run: bash scripts/setup.sh
