---
name: Test setup

on:
  push:
    paths:
      - scripts/setup.sh
      - scripts/install_aqua.sh
      - .aqua/aqua.yml
      - .aqua/imports/*.yml
      - .aqua/aqua-checksums.json
      - .ruby-version
      - Gemfile
      - Gemfile.lock
      - .lefthook.yml
      - .lefthook/**/*.yml
      - .github/workflows/test_setup.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Runtime security for GitHub
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            raw.githubusercontent.com:443
            rubygems.org:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Download aqua
        run: bash scripts/download_aqua.sh

      - name: Add aqua to the environment variable `PATH`
        run: |
          # References
          # https://aquaproj.github.io/docs/tutorial/#install-aqua
          echo "$HOME/.local/share/aquaproj-aqua/bin" >> "$GITHUB_PATH"

      - name: Install Ruby and Bundler
        # yamllint disable-line rule:line-length
        uses: ruby/setup-ruby@5cfe23c062c0aac352e765b1b7cc12ea5255ccc4 # v1.156.0
        with:
          # https://github.com/ruby/setup-ruby/blob/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4/action.yml#L8-L9
          # v1.156.0 Commit on 2023-10-12.
          # Decide the version for Ruby from `.ruby-version` file.
          ruby-version: .ruby-version
          # https://github.com/ruby/setup-ruby/blob/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4/action.yml#L17-L21
          # v1.156.0 Commit on 2023-10-12.
          # - Gemfile.lock
          #   the version of the BUNDLED WITH section
          #   from the Gemfile.lock if it exists.
          #   If the file or section does not exist then the same as 'default'.
          # - default
          #   if the Ruby ships with Bundler 2.2+ as a default gem,
          #   that version is used, otherwise the same as 'latest'.
          bundler: Gemfile.lock
          # https://github.com/ruby/setup-ruby/blob/5cfe23c062c0aac352e765b1b7cc12ea5255ccc4/action.yml#L25
          # v1.156.0 Commit on 2023-10-12.
          # Does not install gems with `bundle install`.
          bundler-cache: false

      - name: Run setup
        run: bash scripts/setup.sh
