---
name: Test setup

on:
  push:
    paths:
      - scripts/setup.sh
      - scripts/install_aqua.sh
      - .aqua/aqua.yml
      - .aqua/imports/*.yml
      - .aqua/aqua-checksums.json
      - .github/workflows/test_setup.yml

permissions: {}

defaults:
  run:
    # Add `-o pipefail` option to bash
    # References
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 5
    steps:
      - name: Create timeline of this GitHub Actions workflow
        # yamllint disable-line rule:line-length
        uses: Kesin11/actions-timeline@baa62e018ca5504e2d617502ce1eacf9171e757a # v2.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download aqua
        run: bash scripts/deps/download_aqua.sh

      - name: Add aqua to the environment variable `PATH`
        run: |
          # References
          # https://aquaproj.github.io/docs/tutorial/#install-aqua
          echo "$HOME/.local/share/aquaproj-aqua/bin" >> "$GITHUB_PATH"

      - name: Run setup
        run: bash scripts/setup.sh
